//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



interface ClassDefinition {
    clrType?: string | undefined;
    caption?: string | undefined;
    description?: string | undefined;
    order?: number | undefined;
    properties?: PropertyDefinition[] | undefined;
    exportedName?: string | undefined;
}

interface PropertyDefinition {
    propertyType: TypeDefinition;
    exportedName: string;
    caption: string;
    description?: string | undefined;
    name: string;
    order?: number | undefined;
}

interface TypeDefinition {
    exportedType?: string | undefined;
    flagsCaption?: string | undefined;
    flagsValue: number;
    caption?: string | undefined;
    description?: string | undefined;
    dictionaryKeyType?: TypeDefinition | undefined;
    dictionaryValueType?: TypeDefinition | undefined;
    arrayElementType?: TypeDefinition | undefined;
    genericTypes?: TypeDefinition[] | undefined;
}

interface EnumDefinition {
    clrType?: string | undefined;
    caption?: string | undefined;
    exportedName?: string | undefined;
    description?: string | undefined;
    order?: number | undefined;
    items?: EnumItemDefinition[] | undefined;
}

interface EnumItemDefinition {
    clrName?: string | undefined;
    caption?: string | undefined;
    description?: string | undefined;
    order?: number | undefined;
    intValue: number;
    stringValue?: string | undefined;
    exportedName?: string | undefined;
    exportedValue?: string | undefined;
}

interface MethodDefinition {
    name?: string | undefined;
    exportedName?: string | undefined;
    caption?: string | undefined;
    description?: string | undefined;
    order?: number | undefined;
    arguments?: MethodArgumentDefinition[] | undefined;
    returnType?: TypeDefinition | undefined;
}

interface EventDefinition extends MethodDefinition {
    keepValueMode: KeepValueMode;
}

enum KeepValueMode {
    FireAndForget = "FireAndForget",
    KeepLastValue = "KeepLastValue",
    KeepWithSeedValue = "KeepWithSeedValue",
}

interface MethodArgumentDefinition extends TypeDefinition {
    exportedName: string;
    clrName: string;
    order: number;
    type: TypeDefinition;
}

interface HubDefinition {
    clrType?: string | undefined;
    caption?: string | undefined;
    description?: string | undefined;
    name?: string | undefined;
    exportedName?: string | undefined;
    methods?: MethodDefinition[] | undefined;
    properties?: PropertyDefinition[] | undefined;
    events?: EventDefinition[] | undefined;
    definitions?: TypeDefinitions | undefined;
}

interface TypeDefinitions {
    classDefinitions?: ClassDefinition[] | undefined;
    enumDefinitions?: EnumDefinition[] | undefined;
}

interface SchemaInfo {
    title: string;
    description?: string | undefined;
    termsOfService?: string | undefined;
    version: string;
}

interface SchemaDocument {
    schemaVersion: string;
    info: SchemaInfo;
    hubs: HubDefinition[];
}